dist: xenial
language: python
python:
    - "3.6"
    - "3.7-dev"

install:
    - pip3 install pipenv
    - pipenv install --dev
    

script:
    - pipenv run pytest -v --disable-pytest-warning
    - pipenv run black --check ./